sudo: required
services:
  - docker

before_install:
  - docker build -t alexyey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexyey/react-test npm test -- --coverage

after_success:
  - docker build -t alexyey/multi-client ./client
  - docker build -t alexyey/multi-nginx ./nginx
  - docker build -t alexyey/multi-server ./server
  - docker build -t alexyey/multi-worker ./worker

# Log in to docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to DockerHub

  - docker push alexyey/multi-client
  - docker push alexyey/multi-nginx
  - docker push alexyey/multi-server
  - docker push alexyey/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-786176943786
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

